# name: PR Checks

# on:
#   pull_request:
#     branches: 
#         - master
#         - feature

# permissions:
#   contents: read

# jobs:
#   precommit:
#     runs-on: ubuntu-latest

#     steps:
#       # Step 1: Check out the code from the PR branch
#       - name: Checkout code
#         uses: actions/checkout@v3

#       # Step 2: Set up Python (required for pre-commit)
#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.x"

#       # Step 3: Install pre-commit
#       - name: Install pre-commit
#         run: |
#           python -m pip install --upgrade pip
#           pip install pre-commit

#       # Step 4: Install pre-commit
#       - name: Install the git hook scripts
#         run: |
#           pre-commit install
          
#       # Step 5: Run pre-commit hooks
#       - name: Run pre-commit
#         run: |
#           pre-commit run --all-files
#           cat /home/runner/.cache/pre-commit/pre-commit.log | tail -20

#       - name: Check the logs
#         run: |
#           cat /home/runner/.cache/pre-commit/pre-commit.log | tail -20


name: pre-commit hooks

on:
  pull_request:
    branches: 
        - main
        - develop
        

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.1